version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    shm_size: 1gb
    volumes:
      - ..:/var/www:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-available
      - ./logs:/var/log
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:8080"